Added Swift Package Manager support
unsplash/unsplash-photopicker-ios pull request #40
Opened 2021-01-05 16:53 UTC by RomanTysiachnik

## Description
- Added `Package.swift` for SPM support;
- Fixed issues in `.xib` files;
- Updated `Readme.md` with instructions for Swift Package Manager.

2021-01-14 12:05 UTC, RomanTysiachnik commented
@ocollet FYI

2021-04-20 22:43 UTC, ocollet commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Views/CheckmarkView.swift
> +          image = UIImage(systemName: "checkmark.circle")
The SF Symbol icon doesn't look good. If anything, it should be in a separate PR. Can you revert this change?

**Bad**
<img width="178" alt="SF Symbol - Bad" src="https://user-images.githubusercontent.com/95189/115472560-1f177080-a208-11eb-8d42-78984ccad288.png">

**Good**
<img width="178" alt="Custom image - Good" src="https://user-images.githubusercontent.com/95189/115472561-1fb00700-a208-11eb-98d2-f01ce667b000.png">

2021-04-20 22:46 UTC, ocollet requested changes
Can you revert the checkmark icon changes?
Everything else is good. 👍

2021-05-17 13:50 UTC, Kondamon commented
@RomanTysiachnik may I kindly ask if you could please remove the requested 2 lines from the review? So this pull request can be merged! It is prohibited to edit your pull request, otherwise I would have done. Thank you!

2021-05-17 15:13 UTC, RomanTysiachnik commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Views/CheckmarkView.swift
> +          image = UIImage(systemName: "checkmark.circle")
@ocollet Yeah, sure!

2021-05-17 15:16 UTC, RomanTysiachnik commented
@ocollet @Kondamon ready!

2021-05-17 19:03 UTC, ocollet approved these changes
Looks good, thanks! 👍

2021-05-17 19:04 UTC, merged